# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    inifile: 
      repo: "puppetlabs/inifile"
      ref: "1.6.0"
    augeasproviders_ssh: "herculesteam/augeasproviders_ssh"
    augeasproviders_core: "herculesteam/augeasproviders_core"
